CREATE TABLE protein_data (
    protein_pair_id INTEGER,
    proteinid1 INTEGER,
    geneid1 INTEGER,
    status1 TEXT,
    proteinid2 INTEGER,
    geneid2 INTEGER,
    status2 TEXT,
    align_seq1 TEXT,
    start_pos1 REAL,
    end_pos1 REAL,
    align_seq2 TEXT,
    start_pos2 REAL,
    end_pos2 REAL,
    match_seq TEXT,
    align_score REAL,
    align_identity REAL,
    align_length REAL,
    align_similarity REAL,
    align_gaps REAL,
    align_identity_count REAL,
    align_similarity_count REAL,
    align_gaps_count REAL,
    comment REAL
);
